###
GET http://localhost:3333/users

###
GET http://localhost:3333/users?search=luan

###
POST http://localhost:3333/users
content-type: application/json

{
  "name": "Luan 3",
  "email": "luancardosoti@gmail.com"
}

###
PUT http://localhost:3333/users/61ccbbfd-4a9b-446e-aa89-3fb3fe974511
content-type: application/json

{
  "name": "Luan 4",
  "email": "luancardosoti@gmail.com"
}

###
GET http://localhost:3333/notFound